// src/components/Nav.tsx
import Logo from "../assets/LOGO.png";
import { motion } from "framer-motion";

const Header = () => {
  return (
    <header className='flex justify-between p-6 bg-white uppercase font-black font-[Montserrat]'>
      <a href='/' className='w-[7dvh] my-auto'>
        <motion.img
          src={Logo.src}
          alt='bar'
          whileHover={{ scale: 1.1, rotate: 12 }}
          whileTap={{ scale: 0.9, rotate: 0 }}
        />
      </a>
      <div className='md:text-2xl text-bmPink-500 flex gap-2 md:gap-8 my-auto'>
        <motion.a
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          href='/blog'
        >
          Blog
        </motion.a>
        <motion.a
          whileHover={{ scale: 1.1 }}
          whileTap={{ scale: 0.9 }}
          href='/mission'
        >
          Mission
        </motion.a>
      </div>
      <motion.div
        className='text-gray-300 cursor-not-allowed text-3xl my-auto'
        whileHover={{ scale: 1.1, rotate: 12 }}
        whileTap={{ scale: 0.9 }}
      >
        <i className='fa-solid fa-shop'></i>
      </motion.div>
    </header>
  );
};

export default Header;

// src/components/Nav.svelte
<script lang="ts">
  import Logo from "../assets/LOGO.png";
</script>

<header
  class="flex justify-between p-6 bg-white uppercase font-black font-[Montserrat]"
>
  <a
    href="/"
    class="w-[7dvh] my-auto hover:scale-105 active:scale-95 ease-in-out duration-150 hover:rotate-12 active:rotate-0"
  >
    <img src={Logo.src} alt="bar" />
  </a>
  <div class="md:text-2xl text-secondary flex gap-2 md:gap-8 my-auto">
    <a
      class="hover:scale-105 active:scale-95 ease-in-out duration-150"
      href="/blog"
    >
      Blog
    </a>
    <a
      class="hover:scale-105 active:scale-95 ease-in-out duration-150"
      href="/mission"
    >
      Mission
    </a>
  </div>
  <div
    class="text-gray-300 cursor-not-allowed text-3xl my-auto hover:scale-105 active:scale-95 ease-in-out duration-150 hover:rotate-12 active:rotate-0"
  >
    <i class="fa-solid fa-shop"></i>
  </div>
</header>
